[project]
name = "cyber-kb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.0",
    "fastapi>=0.115.9",
    "loguru>=0.7.3",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
